name: 🚀 Deploy

on:
  push:
    branches:
      - main
      - dev
    pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 18
      - name: 📥 Install deps
        run: npm install
      - name: 🧹 Lint
        run: npm run lint
  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 18
      - name: 📥 Install deps
        run: npm install
      - name: ʦ TypeScript
        run: npm run typecheck --if-present
  vitest:
  name: ⚡ Vitest
  runs-on: ubuntu-latest
  steps:
    - name: ⬇️ Checkout repo
      uses: actions/checkout@v4
    - name: ⎔ Setup node
      uses: actions/setup-node@v4
      with:
        cache: npm
        node-version: 18
    - name: 📥 Install deps
      run: npm install
    - name: ⚡ Vitest
      run: npm run unit
  playwright:
    name: 🎭 Playwright
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 18
      - name: 📥 Install deps
        run: npm install
      - name: 🎭 Playwright
        run: npm run test:playwright
